export const AUTH_USER = "AUTH_USER";
export const AUTH_FAIL = "AUTH_FAIL";
export const USER_SIGNOUT = "USER_SIGNOUT";
export const FETCH_USER = "FETCH_USER";
export const FETCH_CHAT = "FETCH_CHAT";
export const SOCKET_CONNECT = "SOCKET_CONNECT";
export const SOCKET_CLOSE = "SOCKET_CLOSE";
export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const FETCH_ONLINE_USERS="FETCH_ONLINE_USERS"